http_listen: 0.0.0.0:8080
ws_origin: "http,127.0.0.1:8080"
mongo:
  # mongodb_url: mongodb://172.22.0.2:27017
  mongodb_url: mongodb://0.0.0.0:27017
  db_name: testingwx
app_info:
  appid:
  secret:
seed:
  seed: true
  seed_file: ~/Public/workspace/gowxapi/generate.json
seed_tour:
  seed: true
  tour_path: ~/Public/git_repos/tour-zh
seed_leetcode:
  seed: false
  leetcode_path: ~/Public/workspace/gowxapi/.dist
static_resource:
  fonts_path: ./resource/fonts
  logo_path: ./test/logo.png
  avatar_path: ./test/avatar.png