http_listen: 127.0.0.1:8080
ws_origin: "http,127.0.0.1:8080"
mongo:
  # mongodb_url: mongodb://172.22.0.2:27017
  mongodb_url: mongodb://0.0.0.0:27017
  db_name: testingwx
app_info:
  appid: wxd3947eed2c6b8cbb
  secret: 5bd94e19ae965a3b8957983de0ba2284
seed:
  seed: false
  seed_file: /opt/conf/generate.json
seed_tour:
  seed: false
  tour_path: ~/go/pkg/mod/github.com/!go-zh/tour@v0.0.0-20190515134539-b61130663b4d