mongo:
  mongodb_url: mongodb://119.78.163.141:27017
  db_name: testingwx
app_info:
  appid: wxd3947eed2c6b8cbb
  secret: 5bd94e19ae965a3b8957983de0ba2284
seed:
  seed: true
  seed_file: /opt/conf/generate.json  